# Generated by Django 3.0.5 on 2023-01-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_symbol', models.CharField(max_length=3)),
                ('locale', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectVariableMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.TextField(blank=True, null=True, verbose_name='Application')),
                ('model_name', models.TextField(blank=True, null=True, verbose_name='Model')),
                ('fields', models.TextField(blank=True, null=True, verbose_name='Fields')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Email name')),
                ('template_name', models.TextField(verbose_name='Template Name')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('email_class', models.CharField(blank=True, max_length=25, null=True)),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Subject')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('variables', models.TextField(blank=True, null=True, verbose_name='Merge Variables')),
                ('row_variables', models.TextField(blank=True, null=True, verbose_name='Merge Variables')),
                ('to_email', models.TextField(blank=True, null=True, verbose_name='to_list')),
                ('to_email_function', models.TextField(blank=True, null=True, verbose_name='to_list function')),
                ('from_email', models.TextField(blank=True, null=True, verbose_name='from_list')),
                ('code', models.CharField(choices=[('registration', 'registration'), ('agreement', 'agreement'), ('contact', 'contact'), ('send invoice', 'send invoice'), ('dealership remittance', 'dealership remittance'), ('notification', 'notification'), ('rating', 'rating'), ('thank you', 'thank you'), ('follow up', 'follow up'), ('direct debit setup', 'direct debit setup'), ('dealership report', 'dealership report'), ('brand report', 'brand report'), ('bod report', 'bod report')], max_length=25)),
                ('type', models.CharField(blank=True, choices=[('operational', 'operational'), ('marketing', 'marketing')], max_length=25, null=True)),
                ('related_model_application', models.TextField(blank=True, null=True, verbose_name='related model application')),
                ('related_model_name', models.TextField(blank=True, null=True, verbose_name='related model name')),
                ('attachment_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='attachment type')),
                ('version', models.IntegerField()),
                ('additional_parameters', models.TextField(blank=True, null=True, verbose_name='Additional parameters')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='baseemail.Country')),
            ],
        ),
    ]
