# Generated by Django 3.0.5 on 2023-01-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseemail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='locale',
        ),
    ]
